# Generated by Django 2.2.4 on 2020-02-28 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("orgs", "0058_auto_20190723_2129")]

    operations = [
        migrations.AddField(
            model_name="org",
            name="two_factor_authentication",
            field=models.BooleanField(
                default=False, help_text="Allows you to enable two-factor login for users in the organization"
            ),
        ),
        migrations.AddField(
            model_name="usersettings",
            name="two_factor_authentication",
            field=models.BooleanField(default=False, help_text="Enables two-factor login for the user"),
        ),
    ]
