# Generated by Django 2.2.4 on 2020-03-13 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("orgs", "0059_auto_20200228_1822")]

    operations = [migrations.RemoveField(model_name="org", name="two_factor_authentication")]
