# Generated by Django 2.2.4 on 2020-08-11 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0122_populate_allow_international"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="channelconnection",
            index=models.Index(
                fields=["channel", "status"],
                condition=models.Q(status__in=["W", "R", "I"]),
                name="channels_conn_ch_id_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="channelconnection",
            index=models.Index(
                condition=models.Q(connection_type="V"),
                fields=["channel", "external_id"],
                name="channels_conn_external_id_idx",
            ),
        ),
    ]
