# Generated by Django 2.2.4 on 2020-05-07 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("msgs", "0138_remove_broadcast_recipient_count")]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='next_attempt',
            field=models.DateTimeField(
                help_text='When we should next attempt to deliver this message',
                null=True,
                verbose_name='Next Attempt'
            ),
        ),
    ]
