# Generated by Django 2.2.4 on 2020-05-07 18:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("msgs", "0140_clean_msgs_next_attempt")]

    operations = [
        migrations.AddIndex(
            model_name='msg',
            index=models.Index(
                condition=models.Q(
                    ('direction', 'O'), ('next_attempt__isnull', False), ('status', 'E'), models.Q(_negated=True, msg_type='V')
                ),
                fields=['created_on', 'next_attempt'],
                name='msgs_msg_errored_retry'
            ),
        ),
    ]
