#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

if [ ! -z "${BRANDING_FILES}" ]; then
    git clone $BRANDING_FILES /app/$BRANDING_SLUG/
    mv /app/$BRANDING_SLUG/$BRANDING_SLUG/ /app/static/brands/
fi

python /app/manage.py collectstatic --noinput
if [ "${COMPRESS_ENABLED}" = true ]; then
    python /app/manage.py compress --extension=.haml,.html
fi
python runserver 0.0.0.0:8000