name: Build Develop Push
on:
  push:
    branches:
      - 'dnx'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref:  main
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo "::set-output name=tag::$(git rev-parse --short $GITHUB_SHA)"
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: 869898323958.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.DNX_AK }}
          password: ${{ secrets.DNX_SK }} 
      - name: Build and push - Rapidpro Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: 869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}
          no-cache: true
          build-args: |
            RAPIDPRO_APPS_GIT_URL=https://github.com/Ilhasoft/rapidpro-apps.git
            RAPIDPRO_APPS_GIT_BRANCH=main
            PROTOBUFFERS_URL=https://github.com/Ilhasoft/weni-protobuffers.git
            PROTOBUFFERS_BRANCH=main
            FLOWEDITOR_REPO=https://github.com/Ilhasoft/floweditor.git
            FLOWEDITOR_BRANCH=feature/more-options-in-wait-for-response
            FLOWEDITOR_VERSION=1.13.18
      - name: Build and push - Varnish Image
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile.varnish
          push: true
          tags: 869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}-varnish
          no-cache: true
          build-args: |
            BACKEND_ADDRESS=push-develop:8000
      - name: Check out Argo Manifests
        uses: actions/checkout@master
        with:
          repository: Ilhasoft/kubernetes-manifests
          token: ${{ secrets.TOKEN_CI }}
      - name: Set variable tag for yq
        run: |
            echo "IMAGE_TAG_01=869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_ENV
            echo "IMAGE_TAG_02=869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:$(git rev-parse --short $GITHUB_SHA)-varnish" >> $GITHUB_ENV
      - name: Update image deployment 01
        uses: mikefarah/yq@master
        with:
          cmd: yq e  '.spec.template.spec.containers[0].image = env(IMAGE_TAG_01)' -i rapidpro/nonprod/deployment.yaml
      - name: Update image deployment 02
        uses: mikefarah/yq@master
        with:
          cmd: yq e  '.spec.template.spec.containers[1].image = env(IMAGE_TAG_02)' -i rapidpro/nonprod/deployment.yaml
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.TOKEN_CI }}
          repository: Ilhasoft/kubernetes-manifests
