name: Build Develop Push
on:
  push:
    branches:
      - 'dnx'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref:  develop
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo "::set-output name=tag::$(git rev-parse --short $GITHUB_SHA)"
      - name: Login to ECR
        uses: docker/login-action@v1 
        with:
          registry: 869898323958.dkr.ecr.us-east-1.amazonaws.com
          username: ${{ secrets.DNX_AK }}
          password: ${{ secrets.DNX_SK }} 
      - name: Update Manifest
        uses: mikefarah/yq@master
        run: |
          git clone "https://`${{ secrets.TOKEN_CI }}`@github.com/ilhasoft/kubernetes-manifests"
          cd rapidpro/nonprod
          git config --global user.email "ilhasoft@weni.ai"
          git config --global user.name "ilhasoft"            
          TAG_01=869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}
          TAG_02=869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}-varnish
          yq e  ".spec.template.spec.containers[0].image = \"$TAG_01\"" -i deployment.yaml
          yq e  ".spec.template.spec.containers[1].image = \"$TAG_02\"" -i deployment.yaml
          git add .
          git commit -m "update app tag `${GITHUB_SHA}`"
          git push
      - name: Build and push - Rapidpro Image
        id: docker_build1
        uses: docker/build-push-action@v2
        with:
          context: .
          file: docker/Dockerfile
          push: true
          tags: 869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}
          no-cache: true
          build-args: |
            RAPIDPRO_APPS_GIT_URL=https://github.com/Ilhasoft/rapidpro-apps.git
            RAPIDPRO_APPS_GIT_BRANCH=main
            PROTOBUFFERS_URL=https://github.com/Ilhasoft/weni-protobuffers.git
            PROTOBUFFERS_BRANCH=main
            FLOWEDITOR_REPO=https://github.com/Ilhasoft/floweditor.git
            FLOWEDITOR_BRANCH=feature/more-options-in-wait-for-response
            FLOWEDITOR_VERSION=1.13.18
      - name: Build and push - Varnish Image
        id: docker_build2
        uses: docker/build-push-action@v2
        with:
          context: docker
          file: docker/Dockerfile.varnish
          push: true
          tags: 869898323958.dkr.ecr.us-east-1.amazonaws.com/push-backend:${{ steps.vars.outputs.tag }}-varnish
          no-cache: true
          build-args: |
            BACKEND_ADDRESS=push-develop:8000
