name: Build Develop Push
on:
  push:
    branches:
      - 'dnx'
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: 
      name: develop
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref:  develop
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set output
        id: vars
        run: echo "::set-output name=tag::$(git rev-parse --short $GITHUB_SHA)"
      - name: Check out Argo Manifests
        uses: actions/checkout@master
        with:
          repository: Ilhasoft/kubernetes-manifests
          token: ${{ secrets.TOKEN_CI }}
      - name: Set foobar to cool
        uses: mikefarah/yq@master
        with:
          cmd: yq e  ".spec.template.spec.containers[0].image = \"$GITHUB_SHA\"" -i rapidpro/nonprod/deployment.yaml
